extractable_regions = ["TextRegion",
                       "ImageRegion",
                       "LineDrawingRegion",
                       "GraphicRegion",
                       "TableRegion",
                       "ChartRegion",
                       "MapRegion",
                       "SeparatorRegion",
                       "MathsRegion",
                       "ChemRegion",
                       "MusicRegion",
                       "AdvertRegion",
                       "NoiseRegion",
                       "NoiseRegion",
                       "UnknownRegion",
                       "CustomRegion",
                       "TextLine"]

predictable_regions = ["TextRegion",
                       "TableRegion",
                       "ChartRegion",
                       "MapRegion",
                       "MusicRegion",
                       "AdvertRegion",
                       "UnknownRegion",
                       "CustomRegion",
                       "TextLine",
                       "TableCell"]

TEXT_COUNT_SUPPORTED_ELEMS = ["TextRegion", "TextLine", "Word"]
